export type LandscapeType = "beach" | "forest" | "desert" | "mountains" | "river" | "lake"
export type RegionType   = "north" | "center" | "jerusalem" | "south" | "arava"

export type CampingLocation = {
  id: string
  nameHe: string
  regionHe: string
  region: RegionType
  lat: number
  lng: number
  landscape: LandscapeType
  landscapeHe: string
  amenities: string[]
  overnight: boolean
  fee: boolean
  organized: boolean
  vehicle4x4: boolean
  largeGroupOk: boolean
  descriptionHe: string
  recommendedTents: string[]
  recommendedAccessories: string[]
  parksUrl?: string
}

export const landscapeLabels: Record<LandscapeType, string> = {
  beach:     "חוף ים",
  forest:    "יער",
  desert:    "מדבר",
  mountains: "הרים",
  river:     "נחל / מים",
  lake:      "אגם / כנרת",
}

export const regionLabels: Record<RegionType, string> = {
  north:     "צפון",
  center:    "מרכז",
  jerusalem: "ירושלים והסביבה",
  south:     "דרום",
  arava:     "ערבה / אילת",
}

export const locations: CampingLocation[] = [
  // ─── NORTH ───────────────────────────────────────────────────────────────
  {
    id: "dor-beach",
    nameHe: "חוף דור",
    regionHe: "צפון",
    region: "north",
    lat: 32.614,
    lng: 34.921,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shade", "tables", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "אחד החופים היפים בצפון — חול לבן, מים צלולים ואווירה שקטה. מושלם לאוהל על שפת הים עם נוף ישיר לים התיכון.",
    recommendedTents: ["hub-shelter-pro", "familia", "hub-station"],
    recommendedAccessories: ["sup", "solar-lights", "garlands"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "achziv-beach",
    nameHe: "חוף אכזיב",
    regionHe: "צפון",
    region: "north",
    lat: 33.054,
    lng: 35.101,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shade"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "שמורת טבע עם חוף מדהים בגליל המערבי. כיכרות סלע ים, מים כחולים ושקיעות מרהיבות.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "garlands", "solar-lights"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "horshat-tal",
    nameHe: "חורשת טל",
    regionHe: "צפון",
    region: "north",
    lat: 33.226,
    lng: 35.631,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shade", "tables", "electricity"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חורשת אלונים עתיקה בצפון הגולן — עצים ענקיים, נחל קריר ושטחי דשא ירוקים. אחד מאתרי הקמפינג המאורגנים הטובים בישראל.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "dining-set", "garlands"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "montfort",
    nameHe: "חניון מונפור",
    regionHe: "צפון",
    region: "north",
    lat: 32.973,
    lng: 35.298,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shade", "tables"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "מפגש יופי בגליל — שמורת מונפור עם מצודה צלבנית, יערות עתיקים ואוויר צח של הגליל.",
    recommendedTents: ["familia-pro", "familia"],
    recommendedAccessories: ["fire-pit", "coffee-machine", "garlands"],
  },
  {
    id: "kinneret-north",
    nameHe: "חוף קינרת — צפון",
    regionHe: "צפון",
    region: "north",
    lat: 32.882,
    lng: 35.581,
    landscape: "lake",
    landscapeHe: "אגם / כנרת",
    amenities: ["water", "toilets", "shade", "tables"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "שפת הכנרת — שקיעות בצבעי זהב על פני המים, אוויר ים הכנרת הייחודי וזריחות מדהימות.",
    recommendedTents: ["dome", "familia"],
    recommendedAccessories: ["sup", "star-projector", "solar-lights"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "nahal-amud",
    nameHe: "נחל עמוד",
    regionHe: "צפון",
    region: "north",
    lat: 32.903,
    lng: 35.496,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["shade", "water"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל מפואר בגליל עם בריכות טבעיות ויערות צפופים. מושלם לזוגות שרוצים שקט מוחלט בלב הטבע.",
    recommendedTents: ["hub-station", "dome"],
    recommendedAccessories: ["sup", "coffee-machine", "solar-lights"],
  },
  {
    id: "golan-hermon",
    nameHe: "רמת הגולן — מגדל שמס",
    regionHe: "צפון",
    region: "north",
    lat: 33.275,
    lng: 35.775,
    landscape: "mountains",
    landscapeHe: "הרים",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "רמת הגולן בגובה 1,000+ מ׳ — נוף פנורמי מרהיב, אוויר הרים קריר ושמיים כוכביים שאין להם תחרות.",
    recommendedTents: ["familia-pro", "dome"],
    recommendedAccessories: ["fur-blanket", "telescope", "star-projector"],
  },
  {
    id: "nahariyim",
    nameHe: "נהריים",
    regionHe: "צפון",
    region: "north",
    lat: 32.635,
    lng: 35.602,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "shade", "tables"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "מפגש הירדן עם הירמוך — נוף ירוק ומרענן, מים זורמים ושקט מוחלט בגבול ירדן.",
    recommendedTents: ["hub-station", "familia"],
    recommendedAccessories: ["sup", "garlands", "coffee-machine"],
  },

  // ─── CENTER ───────────────────────────────────────────────────────────────
  {
    id: "palmachim-beach",
    nameHe: "חוף פלמחים",
    regionHe: "מרכז",
    region: "center",
    lat: 31.898,
    lng: 34.684,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shade", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חוף נקי ורחב בשמורת פלמחים — חולות רטובים, גלים מתונים ושקיעות ים תיכוניות קסומות.",
    recommendedTents: ["hub-shelter-pro", "familia"],
    recommendedAccessories: ["sup", "garlands", "solar-lights"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "gador-beach",
    nameHe: "חוף גדור",
    regionHe: "מרכז",
    region: "center",
    lat: 31.764,
    lng: 34.629,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shade"],
    overnight: true,
    fee: true,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חוף יפה ושקט בדרום השפלה — מאורגן, נגיש ומושלם לאירועים ומשפחות גדולות.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["sup", "dining-set", "garlands"],
  },
  {
    id: "ben-shemen",
    nameHe: "יער בן שמן",
    regionHe: "מרכז",
    region: "center",
    lat: 31.967,
    lng: 34.982,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "tables", "shade"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "יער ירוק ומרענן בלב ישראל — מושלם לאירועים, ימי כיף ומשפחות שרוצות להתנתק ליום-יומיים.",
    recommendedTents: ["hub-shelter-pro", "familia-pro"],
    recommendedAccessories: ["fire-pit", "dining-set", "garlands"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "nahal-sorek",
    nameHe: "נחל שורק",
    regionHe: "מרכז",
    region: "center",
    lat: 31.754,
    lng: 35.006,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["shade", "water"],
    overnight: false,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל צנוע עם בריכות ירוקות בין ירושלים לשפלה — אווירה ירוקה ומרגיעה.",
    recommendedTents: ["hub-station", "dome"],
    recommendedAccessories: ["coffee-machine", "solar-lights"],
  },
  {
    id: "sharigim",
    nameHe: "חניון שריגים",
    regionHe: "מרכז",
    region: "center",
    lat: 31.828,
    lng: 34.957,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "tables", "shade"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון מאורגן ונוח בין השפלה להרים — עצים גדולים, שטחי דשא ומשפחות מסביב לאש.",
    recommendedTents: ["familia-pro", "familia"],
    recommendedAccessories: ["fire-pit", "dining-set", "speaker"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },

  // ─── JERUSALEM ────────────────────────────────────────────────────────────
  {
    id: "jerusalem-forest",
    nameHe: "יער ירושלים",
    regionHe: "ירושלים",
    region: "jerusalem",
    lat: 31.783,
    lng: 35.163,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["shade", "tables", "water"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "יער ירושלמי אורנים עם גובה 800 מ׳ — לילות קרירים, כוכבים בהירים ואווירה רומנטית ייחודית.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["fur-blanket", "fire-pit", "telescope"],
  },
  {
    id: "ein-hemed",
    nameHe: "גן לאומי עין חמד",
    regionHe: "ירושלים",
    region: "jerusalem",
    lat: 31.803,
    lng: 35.104,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shade", "tables"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "גן לאומי יפהפה על גדות נחל שורק — עצים ירוקים, מים צוננים וקרבה מלאה לירושלים.",
    recommendedTents: ["hub-shelter-pro", "familia"],
    recommendedAccessories: ["dining-set", "garlands", "coffee-machine"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "nahal-prat",
    nameHe: "נחל פרת — עין פרת",
    regionHe: "ירושלים",
    region: "jerusalem",
    lat: 31.856,
    lng: 35.376,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "shade"],
    overnight: false,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל מדברי עם מים שקופים בין מדבר יהודה — ניגוד מדהים בין הירוק הפורה לסלע הסהרוני.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "coffee-machine"],
  },
  {
    id: "maaleh-hahamisha",
    nameHe: "מעלה החמישה",
    regionHe: "ירושלים",
    region: "jerusalem",
    lat: 31.812,
    lng: 35.118,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shade", "tables", "electricity"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "קיבוץ ואתר נופש בהרי ירושלים — שטח פתוח בין עצי אורן, נוף מרהיב לשפלה וכוכבים ירושלמיים.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "fur-blanket", "garlands"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },

  // ─── SOUTH ────────────────────────────────────────────────────────────────
  {
    id: "ein-gedi",
    nameHe: "עין גדי",
    regionHe: "דרום",
    region: "south",
    lat: 31.464,
    lng: 35.391,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shade", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "נאות מדבר על שפת ים המלח — שמורת טבע עם מפלים, יעלים פראיים ולילות מדבר קסומים מתחת לשמיים.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "masada",
    nameHe: "מצדה",
    regionHe: "דרום",
    region: "south",
    lat: 31.316,
    lng: 35.354,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "בצל מצדה — לילה מדברי בגובה ים המלח עם זריחה היסטורית על המדבר. חוויה שלא תישכח.",
    recommendedTents: ["dome", "familia"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "dead-sea-north",
    nameHe: "חוף ים המלח — עין בוקק",
    regionHe: "דרום",
    region: "south",
    lat: 31.210,
    lng: 35.378,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shade", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "ים המלח הכחול — שחייה ללא מאמץ, בוץ ריפוי ושקיעות ענקיות על ההרים ממול. חוויה ייחודית בעולם.",
    recommendedTents: ["hub-station", "familia"],
    recommendedAccessories: ["solar-lights", "garlands", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "ramon-crater",
    nameHe: "מכתש רמון",
    regionHe: "דרום",
    region: "south",
    lat: 30.606,
    lng: 34.818,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "המכתש הגדול בעולם — כוכבים בדרגה אחרת, שקטים שאין להם אח ורע, ונוף גיאולוגי עוצר נשימה.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "sde-boker",
    nameHe: "שדה בוקר",
    regionHe: "דרום",
    region: "south",
    lat: 30.873,
    lng: 34.784,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shade"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נגב העמוק — קניון צין, מפל ניצנה, הביוגרמה של בן גוריון. מקום של שקט, מחשבה ואוויר מדברי נקי.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "coffee-machine", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "nahal-tzihor",
    nameHe: "נחל ציחור",
    regionHe: "דרום",
    region: "south",
    lat: 30.950,
    lng: 34.919,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["shade"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "ואדי מדברי פראי בנגב — לא מאורגן, לא ידוע, ובדיוק בגלל זה מושלם. כוכבים ושקט מוחלט.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "coffee-machine"],
  },
  {
    id: "nahal-paran",
    nameHe: "נחל פארן",
    regionHe: "דרום",
    region: "south",
    lat: 30.350,
    lng: 35.100,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "נחל הפארן הגדול — ואדי ענקי עם צוקים אדומים, עמוק בנגב. לאוהבי ה-off-road האמיתי.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "arad-desert",
    nameHe: "מדבר ערד",
    regionHe: "דרום",
    region: "south",
    lat: 31.260,
    lng: 35.213,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "נגב פתוח מול הרי ים המלח — נוף ענק, לילות מדבר שקטים ואפשרות לצאת לטיולים בנחלים הסמוכים.",
    recommendedTents: ["familia", "dome"],
    recommendedAccessories: ["star-projector", "telescope", "fire-pit"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },

  // ─── ARAVA / EILAT ────────────────────────────────────────────────────────
  {
    id: "timna",
    nameHe: "פארק תמנע",
    regionHe: "ערבה",
    region: "arava",
    lat: 29.793,
    lng: 34.979,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shade", "electricity"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "עמקי הנחושת הנגביים — כוכב הדרום של הקמפינג בישראל. נוף מדהים, פטריות סלע ושמיים פתוחים ב-360°.",
    recommendedTents: ["dome", "familia"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "eilat-north-beach",
    nameHe: "חוף אילת — צפון",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 29.558,
    lng: 34.949,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower", "shade"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "אגם האלמוגים — ים אדום צלול, שנורקלינג עוצר נשימה וחמימות שאין לה מתחרה בינואר. חוויה בינלאומית.",
    recommendedTents: ["hub-shelter-pro", "familia"],
    recommendedAccessories: ["sup", "solar-lights", "garlands"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "eilat-coral-beach",
    nameHe: "חוף האלמוגים אילת",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 29.508,
    lng: 34.921,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower", "shade", "tables"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "שמורת הים האלמוגים — אחת מ-4 שמורות האלמוגים בים האדום. מים כחולים צלולים ושקיעות דרמטיות.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "telescope", "solar-lights"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "neot-hakikar",
    nameHe: "נאות הכיכר",
    regionHe: "ערבה",
    region: "arava",
    lat: 30.965,
    lng: 35.400,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "ירקון מדברי בלב הערבה — שדות תמרים, נחל ים המלח וצמחייה מפתיעה בלב המדבר הצחיח.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "coffee-machine"],
  },
  {
    id: "ein-yahav",
    nameHe: "עין יהב",
    regionHe: "ערבה",
    region: "arava",
    lat: 30.613,
    lng: 35.213,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "shade"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "לב הערבה הפתוחה — שקט מוחלט, כוכבים ענקיים וטמפרטורות נעימות בלילה. מקום להתרחק מהכל.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "hatzeva",
    nameHe: "חצבה",
    regionHe: "ערבה",
    region: "arava",
    lat: 30.773,
    lng: 35.239,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "תחנה בלב הערבה — קרבה לנחל קידרון ופארק תמנע. שמיים ערביים פנומנליים לצפייה בכוכבים.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },

  // ─── FREE OVERNIGHT — חניוני לילה ללא תשלום ──────────────────────────────
  {
    id: "dragot-cliffs",
    nameHe: "מצוקי דרגות",
    regionHe: "דרום",
    region: "south",
    lat: 31.347,
    lng: 35.432,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "מצוקים עוצרי נשימה מעל ים המלח — לילה פראי בגובה 400 מ׳ מעל ים המלח עם נוף שאין שני לו. מהמקומות הדרמטיים ביותר בישראל.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "nahal-taninim",
    nameHe: "נחל תנינים",
    regionHe: "צפון",
    region: "north",
    lat: 32.503,
    lng: 34.895,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "shade", "tables"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "גן לאומי עם נחל ירוק ומרהיב על החוף הכרמלי — שפע צומח, מים זורמים ושקיעות ים תיכוניות מהממות.",
    recommendedTents: ["hub-station", "familia"],
    recommendedAccessories: ["garlands", "coffee-machine", "sup"],
  },
  {
    id: "carmel-beit-oren",
    nameHe: "שמורת הכרמל — בית אורן",
    regionHe: "צפון",
    region: "north",
    lat: 32.721,
    lng: 34.989,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["shade", "tables"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "לב שמורת הכרמל — עצי אורן ענקיים, אוויר צח, ציפורים ותצפית על המפרץ. נסתר, שקט ומיוחד.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "fur-blanket", "telescope"],
  },
  {
    id: "nahal-shagur",
    nameHe: "נחל שגור",
    regionHe: "צפון",
    region: "north",
    lat: 33.003,
    lng: 35.238,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "shade"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל סמוי בגליל העליון — מים צוננים, שמורת טבע ירוקה ואוירה של גן עדן מוסתר. פחות ידוע, יותר מיוחד.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "coffee-machine", "solar-lights"],
  },
  {
    id: "makhtesh-katan",
    nameHe: "מכתש קטן",
    regionHe: "דרום",
    region: "south",
    lat: 30.951,
    lng: 35.018,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "המכתש הקטן מהשלושה — בלי תיירים, בלי רעש. כוכבים בגודל שלא תראו בשום מקום אחר. מדבר אמיתי.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "nahal-shikmim",
    nameHe: "נחל שקמים — גן לאומי",
    regionHe: "מרכז",
    region: "center",
    lat: 31.654,
    lng: 34.592,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "shade", "tables"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "גן לאומי ירוק בין תל אביב לאשקלון — עצים, מים וצל. מושלם למשפחות שרוצות טבע קרוב לבית.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["dining-set", "garlands", "coffee-machine"],
  },
  {
    id: "golan-gamla",
    nameHe: "גמלא — הגולן",
    regionHe: "צפון",
    region: "north",
    lat: 32.903,
    lng: 35.753,
    landscape: "mountains",
    landscapeHe: "הרים",
    amenities: ["water", "shade", "tables"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "שמורת גמלא בגולן — נשרים פורחים מעל הנחל, קניון עמוק ונוף לכנרת. אחד המקומות הציוריים ביותר בישראל.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "fur-blanket", "coffee-machine"],
  },
  {
    id: "arava-gorge",
    nameHe: "נחל צאלים — ערבה",
    regionHe: "דרום",
    region: "south",
    lat: 31.118,
    lng: 35.363,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "ואדי מדברי פראי בין הים המלח לשדה הנגב — צוקים אדומים, שקט מוחלט ושמיים בלתי נשכחים.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["star-projector", "telescope", "fur-blanket"],
  },
]

export function getLocationsByRegion(region: RegionType): CampingLocation[] {
  return locations.filter((l) => l.region === region)
}

export function getLocationsByLandscape(landscape: LandscapeType): CampingLocation[] {
  return locations.filter((l) => l.landscape === landscape)
}

export const amenityLabels: Record<string, string> = {
  water:       "מים",
  toilets:     "שירותים",
  shade:       "צל",
  tables:      "שולחנות",
  electricity: "חשמל",
  shower:      "מקלחות",
  glamping:    "גלמפינג",
}
