export type LandscapeType = "beach" | "forest" | "desert" | "mountains" | "river" | "lake"
export type RegionType   = "north" | "golan" | "center" | "jerusalem" | "south" | "arava"

export type CampingLocation = {
  id: string
  nameHe: string
  regionHe: string
  region: RegionType
  lat: number
  lng: number
  landscape: LandscapeType
  landscapeHe: string
  amenities: string[]
  overnight: boolean
  fee: boolean
  organized: boolean
  vehicle4x4: boolean
  largeGroupOk: boolean
  /** שטח פרטי · ההזמנה מול בעל השטח */
  privateLand?: boolean
  descriptionHe: string
  recommendedTents: string[]
  recommendedAccessories: string[]
  parksUrl?: string
  /** תצלומים · מהמסד. בקוד מגיע מ-lib/location-photos.ts */
  photos?: string[]
}

export const landscapeLabels: Record<LandscapeType, string> = {
  beach:     "חוף ים",
  forest:    "יער",
  desert:    "מדבר",
  mountains: "הררי",
  river:     "נחל / מים",
  lake:      "אגם / כנרת",
}

export const regionLabels: Record<RegionType, string> = {
  north:     "צפון",
  golan:     "גולן",
  center:    "מרכז",
  jerusalem: "ירושלים והסביבה",
  south:     "דרום",
  arava:     "ערבה / אילת",
}

/**
 * לפי המסמך של רז "עמוד לוקיישנים" (25.09.2026) ובאותו סדר:
 * קודם לינת לילה מאושרת, אחר כך קמפינג יום בלבד, ובסוף שטחים פרטיים.
 */
export const locations: CampingLocation[] = [
  {
    id: "achziv-beach",
    nameHe: "חוף אכזיב",
    regionHe: "צפון",
    region: "north",
    lat: 33.054,
    lng: 35.101,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "שמורת טבע עם חוף מדהים בגליל המערבי. כיכרות סלע ים, מים כחולים ושקיעות מרהיבות.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "garlands", "lanterns"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "horshat-tal",
    nameHe: "חורשת טל",
    regionHe: "צפון",
    region: "north",
    lat: 33.226,
    lng: 35.631,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shower", "electricity"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חורשת אלונים עתיקה בצפון הגולן · עצים ענקיים, נחל קריר ושטחי דשא ירוקים.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "dining-set", "garlands"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "montfort",
    nameHe: "חניון מונפור · יער גורן",
    regionHe: "צפון",
    region: "north",
    lat: 32.973,
    lng: 35.298,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "מפגש יופי בגליל · שמורת מונפור עם מצודה צלבנית, יערות עתיקים ואוויר צח של הגליל.",
    recommendedTents: ["familia-pro", "familia"],
    recommendedAccessories: ["fire-pit", "coffee-machine", "garlands"],
    parksUrl: "https://www.kkl.org.il/recreation_areas_overnight_2022/",
  },
  {
    id: "nahal-amud",
    nameHe: "נחל עמוד",
    regionHe: "צפון",
    region: "north",
    lat: 32.903,
    lng: 35.496,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל מפואר בגליל עם בריכות טבעיות ויערות צפופים. מושלם לזוגות שרוצים שקט מוחלט בלב הטבע.",
    recommendedTents: ["hub-station", "dome"],
    recommendedAccessories: ["sup", "coffee-machine", "lanterns"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "golan-hermon",
    nameHe: "רמת הגולן · עין זיוון",
    regionHe: "גולן",
    region: "golan",
    lat: 33.09,
    lng: 35.787,
    landscape: "mountains",
    landscapeHe: "הררי",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "רמת הגולן בגובה 1,000+ מ׳ · נוף פנורמי מרהיב, אוויר הרים קריר ושמיים כוכביים שאין להם תחרות.",
    recommendedTents: ["familia-pro", "dome"],
    recommendedAccessories: ["fur-blanket", "telescope", "star-projector"],
  },
  {
    id: "ben-shemen",
    nameHe: "יער בן שמן",
    regionHe: "מרכז",
    region: "center",
    lat: 31.967,
    lng: 34.982,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "יער ירוק ומרענן בלב ישראל · מושלם לאירועים, ימי כיף ומשפחות שרוצות להתנתק ליום-יומיים.",
    recommendedTents: ["hub-shelter-pro", "familia-pro"],
    recommendedAccessories: ["fire-pit", "dining-set", "garlands"],
    parksUrl: "https://www.kkl.org.il/parking_lot_overnight_ben_shemen/",
  },
  {
    id: "nahal-sorek",
    nameHe: "שפך נחל שורק",
    regionHe: "מרכז",
    region: "center",
    lat: 31.935,
    lng: 34.7,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל צנוע עם בריכות ירוקות בין ירושלים לשפלה · אווירה ירוקה ומרגיעה.",
    recommendedTents: ["hub-station", "dome"],
    recommendedAccessories: ["coffee-machine", "lanterns"],
  },
  {
    id: "sharigim",
    nameHe: "חניון שריגים",
    regionHe: "מרכז",
    region: "center",
    lat: 31.828,
    lng: 34.957,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: [],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון מאורגן ונוח בין השפלה להרים · עצים גדולים, שטחי דשא ומשפחות מסביב לאש.",
    recommendedTents: ["familia-pro", "familia"],
    recommendedAccessories: ["fire-pit", "dining-set", "speaker"],
  },
  {
    id: "jerusalem-forest",
    nameHe: "יער ירושלים · בני ציון",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.783,
    lng: 35.163,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "יער ירושלמי אורנים עם גובה 800 מ׳ · לילות קרירים, כוכבים בהירים ואווירה רומנטית ייחודית.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["fur-blanket", "fire-pit", "telescope"],
    parksUrl: "https://www.kkl.org.il/parking_lot_overnight_bnei_tzion/",
  },
  {
    id: "nahal-prat",
    nameHe: "נחל פרת · עין פרת",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.856,
    lng: 35.376,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל מדברי עם מים שקופים בין מדבר יהודה · ניגוד מדהים בין הירוק הפורה לסלע הסהרוני.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "coffee-machine"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "ein-gedi",
    nameHe: "עין גדי",
    regionHe: "דרום",
    region: "south",
    lat: 31.464,
    lng: 35.391,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "נאות מדבר על שפת ים המלח · שמורת טבע עם מפלים, יעלים פראיים ולילות מדבר קסומים מתחת לשמיים.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "masada",
    nameHe: "מצדה",
    regionHe: "דרום",
    region: "south",
    lat: 31.316,
    lng: 35.354,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "בצל מצדה · לילה מדברי בגובה ים המלח עם זריחה היסטורית על המדבר.",
    recommendedTents: ["dome", "familia"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "ramon-crater",
    nameHe: "מכתש רמון · חאן בארות",
    regionHe: "דרום",
    region: "south",
    lat: 30.606,
    lng: 34.818,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "המכתש הגדול בעולם · כוכבים בדרגה אחרת, שקטים שאין להם אח ורע, ונוף גיאולוגי עוצר נשימה.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "sde-boker",
    nameHe: "שדה בוקר (סרפנטין)",
    regionHe: "דרום",
    region: "south",
    lat: 30.873,
    lng: 34.784,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נגב העמוק · קניון צין, מפל ניצנה, הביוגרמה של בן גוריון.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "coffee-machine", "fur-blanket"],
  },
  {
    id: "nahal-tzihor",
    nameHe: "נחל ציחור",
    regionHe: "דרום",
    region: "south",
    lat: 30.95,
    lng: 34.919,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "ואדי מדברי פראי בנגב · לא מאורגן, לא ידוע, ובדיוק בגלל זה מושלם.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "coffee-machine"],
  },
  {
    id: "nahal-paran",
    nameHe: "נחל פארן",
    regionHe: "דרום",
    region: "south",
    lat: 30.35,
    lng: 35.1,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "נחל הפארן הגדול · ואדי ענקי עם צוקים אדומים, עמוק בנגב.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "arad-desert",
    nameHe: "מדבר ערד · תל ערד",
    regionHe: "דרום",
    region: "south",
    lat: 31.26,
    lng: 35.213,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "נגב פתוח מול הרי ים המלח · נוף ענק, לילות מדבר שקטים ואפשרות לצאת לטיולים בנחלים הסמוכים.",
    recommendedTents: ["familia", "dome"],
    recommendedAccessories: ["star-projector", "telescope", "fire-pit"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "carmel-beit-oren",
    nameHe: "חוות משמר הכרמל",
    regionHe: "צפון",
    region: "north",
    lat: 32.721,
    lng: 34.989,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shower"],
    overnight: true,
    fee: true,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "לב שמורת הכרמל · עצי אורן ענקיים, אוויר צח, ציפורים ותצפית על המפרץ.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "fur-blanket", "telescope"],
    parksUrl: "https://www.parks.org.il/הזמנות-לחניוני-לילה/",
  },
  {
    id: "makhtesh-katan",
    nameHe: "מכתש קטן (שער אשמדאי)",
    regionHe: "דרום",
    region: "south",
    lat: 30.951,
    lng: 35.018,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water"],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "המכתש הקטן מהשלושה · בלי תיירים, בלי רעש. כוכבים בגודל שלא תראו בשום מקום אחר.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "arava-gorge",
    nameHe: "נחל צאלים · ערבה",
    regionHe: "דרום",
    region: "south",
    lat: 31.118,
    lng: 35.363,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    descriptionHe: "ואדי מדברי פראי בין הים המלח לשדה הנגב · צוקים אדומים, שקט מוחלט ושמיים בלתי נשכחים.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["star-projector", "telescope", "fur-blanket"],
  },
  {
    id: "shoresh",
    nameHe: "חניון לילה שורש",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.797,
    lng: 35.064,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון יער ליד שורש בהרי ירושלים · אתר פיקניק ומסלולי אופניים בסביבה.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "dining-set"],
    parksUrl: "https://www.kkl.org.il/travel/campground_center/",
  },
  {
    id: "har-eitan",
    nameHe: "הר איתן · יער סטף",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.769,
    lng: 35.123,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון לילה ביער סטף עם נוף הררי · תיאום מראש נדרש.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["fur-blanket", "telescope"],
    parksUrl: "https://www.kkl.org.il/parking_lot_overnight_eithan/",
  },
  {
    id: "nes-harim",
    nameHe: "נס הרים · פארק עצמאות ארה\"ב",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.734,
    lng: 35.057,
    landscape: "mountains",
    landscapeHe: "הררי",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון לילה על רכס נוף בפארק עצמאות ארה\"ב.",
    recommendedTents: ["familia"],
    recommendedAccessories: ["fire-pit", "fur-blanket"],
    parksUrl: "https://www.kkl.org.il/travel/campground_center/",
  },
  {
    id: "masua",
    nameHe: "משואה · פארק בריטניה",
    regionHe: "מרכז",
    region: "center",
    lat: 31.672,
    lng: 34.968,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: true,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון לילה בפארק בריטניה, קרוב לירושלים והשפלה.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["dining-set", "speaker"],
    parksUrl: "https://www.kkl.org.il/travel/campground_center/",
  },
  {
    id: "aminadav",
    nameHe: "סעדים · יער עמינדב",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.756,
    lng: 35.131,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון לילה שקט ביער עמינדב, הרי ירושלים.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "fur-blanket"],
    parksUrl: "https://www.kkl.org.il/travel/campground_center/",
  },
  {
    id: "bar-giora",
    nameHe: "בר גיורא · פארק בגין",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.735,
    lng: 35.082,
    landscape: "mountains",
    landscapeHe: "הררי",
    amenities: [],
    overnight: true,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חניון לילה היסטורי בפארק בגין, נוף להרי יהודה.",
    recommendedTents: ["familia", "hub-station"],
    recommendedAccessories: ["fire-pit", "telescope"],
    parksUrl: "https://www.kkl.org.il/travel/campground_center/",
  },
  {
    id: "dor-beach",
    nameHe: "חוף דור",
    regionHe: "צפון",
    region: "north",
    lat: 32.614,
    lng: 34.921,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "אחד החופים היפים בצפון · חול לבן, מים צלולים ואווירה שקטה.",
    recommendedTents: ["hub-shelter-pro", "familia", "hub-station"],
    recommendedAccessories: ["sup", "lanterns", "garlands"],
  },
  {
    id: "kinneret-north",
    nameHe: "חוף קינרת · צפון",
    regionHe: "צפון",
    region: "north",
    lat: 32.882,
    lng: 35.581,
    landscape: "lake",
    landscapeHe: "אגם / כנרת",
    amenities: ["water", "toilets"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "שפת הכנרת · שקיעות בצבעי זהב על פני המים, אוויר ים הכנרת הייחודי וזריחות מדהימות.",
    recommendedTents: ["dome", "familia"],
    recommendedAccessories: ["sup", "star-projector", "lanterns"],
    parksUrl: "https://ikinneret.org.il/",
  },
  {
    id: "nahariyim",
    nameHe: "נהריים",
    regionHe: "צפון",
    region: "north",
    lat: 32.635,
    lng: 35.602,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water"],
    overnight: false,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "מפגש הירדן עם הירמוך · נוף ירוק ומרענן, מים זורמים ושקט מוחלט בגבול ירדן.",
    recommendedTents: ["hub-station", "familia"],
    recommendedAccessories: ["sup", "garlands", "coffee-machine"],
  },
  {
    id: "palmachim-beach",
    nameHe: "חוף פלמחים",
    regionHe: "מרכז",
    region: "center",
    lat: 31.898,
    lng: 34.684,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חוף נקי ורחב בשמורת פלמחים · חולות רטובים, גלים מתונים ושקיעות ים תיכוניות קסומות.",
    recommendedTents: ["hub-shelter-pro", "familia"],
    recommendedAccessories: ["sup", "garlands", "lanterns"],
  },
  {
    id: "gador-beach",
    nameHe: "חוף גדור",
    regionHe: "מרכז",
    region: "center",
    lat: 31.764,
    lng: 34.629,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets"],
    overnight: false,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חוף יפה ושקט בדרום השפלה · מאורגן, נגיש ומושלם לאירועים ומשפחות גדולות.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["sup", "dining-set", "garlands"],
  },
  {
    id: "ein-hemed",
    nameHe: "גן לאומי עין חמד",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.803,
    lng: 35.104,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "גן לאומי יפהפה על גדות נחל שורק · עצים ירוקים, מים צוננים וקרבה מלאה לירושלים.",
    recommendedTents: ["hub-shelter-pro", "familia"],
    recommendedAccessories: ["dining-set", "garlands", "coffee-machine"],
  },
  {
    id: "maaleh-hahamisha",
    nameHe: "מעלה החמישה",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.812,
    lng: 35.118,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "electricity"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "קיבוץ ואתר נופש בהרי ירושלים · שטח פתוח בין עצי אורן, נוף מרהיב לשפלה וכוכבים ירושלמיים.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["fire-pit", "fur-blanket", "garlands"],
  },
  {
    id: "dead-sea-north",
    nameHe: "ים המלח · עין בוקק",
    regionHe: "דרום",
    region: "south",
    lat: 31.21,
    lng: 35.378,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "ים המלח הכחול · שחייה ללא מאמץ, בוץ ריפוי ושקיעות ענקיות על ההרים ממול.",
    recommendedTents: ["hub-station", "familia"],
    recommendedAccessories: ["lanterns", "garlands", "fur-blanket"],
  },
  {
    id: "timna",
    nameHe: "פארק תמנע",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 29.793,
    lng: 34.979,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shower", "electricity"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "עמקי הנחושת הנגביים · כוכב הדרום של הקמפינג בישראל. נוף מדהים, פטריות סלע ושמיים פתוחים ב-360°.",
    recommendedTents: ["dome", "familia"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://parktimna.co.il/",
  },
  {
    id: "eilat-north-beach",
    nameHe: "חוף אילת · צפון",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 29.558,
    lng: 34.949,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "ים אדום צלול, שנורקלינג עוצר נשימה וחמימות שאין לה מתחרה בינואר.",
    recommendedTents: ["hub-shelter-pro", "familia"],
    recommendedAccessories: ["sup", "lanterns", "garlands"],
  },
  {
    id: "eilat-coral-beach",
    nameHe: "חוף האלמוגים אילת",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 29.508,
    lng: 34.921,
    landscape: "beach",
    landscapeHe: "חוף ים",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "שמורת הים האלמוגים · אחת מ-4 שמורות האלמוגים בים האדום. מים כחולים צלולים ושקיעות דרמטיות.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "telescope", "lanterns"],
  },
  {
    id: "neot-hakikar",
    nameHe: "נאות הכיכר",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 30.965,
    lng: 35.4,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: false,
    fee: true,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "ירקון מדברי בלב הערבה · שדות תמרים, נחל ים המלח וצמחייה מפתיעה בלב המדבר הצחיח.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "coffee-machine"],
  },
  {
    id: "ein-yahav",
    nameHe: "עין יהב",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 30.613,
    lng: 35.213,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water"],
    overnight: false,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "לב הערבה הפתוחה · שקט מוחלט, כוכבים ענקיים וטמפרטורות נעימות בלילה.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
  },
  {
    id: "hatzeva",
    nameHe: "חצבה",
    regionHe: "ערבה / אילת",
    region: "arava",
    lat: 30.773,
    lng: 35.239,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "תחנה בלב הערבה · קרבה לנחל קידרון ופארק תמנע. שמיים ערביים פנומנליים לצפייה בכוכבים.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["star-projector", "telescope", "fur-blanket"],
  },
  {
    id: "nahal-taninim",
    nameHe: "נחל תנינים",
    regionHe: "צפון",
    region: "north",
    lat: 32.503,
    lng: 34.895,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water"],
    overnight: false,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "גן לאומי עם נחל ירוק ומרהיב על החוף הכרמלי · שפע צומח, מים זורמים ושקיעות ים תיכוניות מהממות.",
    recommendedTents: ["hub-station", "familia"],
    recommendedAccessories: ["garlands", "coffee-machine", "sup"],
  },
  {
    id: "nahal-shagur",
    nameHe: "נחל שגור",
    regionHe: "צפון",
    region: "north",
    lat: 33.003,
    lng: 35.238,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water"],
    overnight: false,
    fee: false,
    organized: false,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "נחל סמוי בגליל העליון · מים צוננים, שמורת טבע ירוקה ואוירה של גן עדן מוסתר.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "coffee-machine", "lanterns"],
  },
  {
    id: "nahal-shikmim",
    nameHe: "נחל שקמים · גן לאומי",
    regionHe: "מרכז",
    region: "center",
    lat: 31.654,
    lng: 34.592,
    landscape: "river",
    landscapeHe: "נחל / מים",
    amenities: ["water"],
    overnight: false,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "גן לאומי ירוק בין תל אביב לאשקלון · עצים, מים וצל. מושלם למשפחות שרוצות טבע קרוב לבית.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["dining-set", "garlands", "coffee-machine"],
  },
  {
    id: "golan-gamla",
    nameHe: "שמורת גמלא",
    regionHe: "גולן",
    region: "golan",
    lat: 32.903,
    lng: 35.753,
    landscape: "mountains",
    landscapeHe: "הררי",
    amenities: ["toilets"],
    overnight: false,
    fee: false,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: false,
    descriptionHe: "שמורת גמלא בגולן · נשרים פורחים מעל הנחל, קניון עמוק ונוף לכנרת.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["telescope", "fur-blanket", "coffee-machine"],
  },
  {
    id: "hukuk-north",
    nameHe: "חוף חוקוק צפוני",
    regionHe: "צפון",
    region: "north",
    lat: 32.878,
    lng: 35.515,
    landscape: "lake",
    landscapeHe: "אגם / כנרת",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "\"החוף הירוק\" · חוף מצטיין באיכות סביבתית בצפון הכנרת, לינת שטח על הדשא (לא על חוף הרחצה המוכרז).",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["sup", "lanterns"],
    parksUrl: "https://ikinneret.org.il/",
  },
  {
    id: "susita-beach",
    nameHe: "חוף סוסיתא",
    regionHe: "צפון",
    region: "north",
    lat: 32.79,
    lng: 35.64,
    landscape: "lake",
    landscapeHe: "אגם / כנרת",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "מפרץ יפהפה בגדה המזרחית של הכנרת, צל רב · מתאים ללינת אוהלים ופעילות משפחתית.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["dining-set", "sup"],
    parksUrl: "https://ikinneret.org.il/",
  },
  {
    id: "duga-beach",
    nameHe: "חוף דוגה",
    regionHe: "צפון",
    region: "north",
    lat: 32.865,
    lng: 35.636,
    landscape: "lake",
    landscapeHe: "אגם / כנרת",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "כ-100 דונם בצפון-מזרח הכנרת, שופץ לאחרונה · שטח נרחב לקבוצות גדולות.",
    recommendedTents: ["familia-pro", "hub-shelter-pro"],
    recommendedAccessories: ["dining-set", "speaker"],
    parksUrl: "https://ikinneret.org.il/",
  },
  {
    id: "gofra-beach",
    nameHe: "חוף גופרה",
    regionHe: "צפון",
    region: "north",
    lat: 32.772,
    lng: 35.641,
    landscape: "lake",
    landscapeHe: "אגם / כנרת",
    amenities: ["water", "toilets", "shower"],
    overnight: false,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    descriptionHe: "חוף מפותח עם מעיין גופרה (מי מרים) חמים, טיילת עץ · חוויה ייחודית בכנרת.",
    recommendedTents: ["dome", "hub-station"],
    recommendedAccessories: ["fur-blanket", "lanterns"],
    parksUrl: "https://ikinneret.org.il/",
  },
  {
    id: "dragot-cliffs",
    nameHe: "מצוקי דרגות",
    regionHe: "דרום",
    region: "south",
    lat: 31.347,
    lng: 35.432,
    landscape: "desert",
    landscapeHe: "מדבר",
    amenities: ["water", "toilets", "shower"],
    overnight: true,
    fee: true,
    organized: false,
    vehicle4x4: true,
    largeGroupOk: false,
    privateLand: true,
    descriptionHe: "מצוקים עוצרי נשימה מעל ים המלח · לילה פראי בגובה 400 מ׳ מעל ים המלח עם נוף שאין שני לו.",
    recommendedTents: ["dome"],
    recommendedAccessories: ["telescope", "star-projector", "fur-blanket"],
    parksUrl: "https://www.gocamping.co.il/מצוקי-דרגות-גלמפינג-קמפינג-וצימרים/",
  },
  {
    id: "peace-forest",
    nameHe: "קמפינג יער השלום, ירושלים",
    regionHe: "ירושלים והסביבה",
    region: "jerusalem",
    lat: 31.763,
    lng: 35.232,
    landscape: "forest",
    landscapeHe: "יער",
    amenities: ["water", "toilets", "shower"],
    overnight: true,
    fee: true,
    organized: true,
    vehicle4x4: false,
    largeGroupOk: true,
    privateLand: true,
    descriptionHe: "קמפינג עירוני מאובזר בלב יער בירושלים · מטבח משותף, מקלחות ומתחמי פעילות לקבוצות ומשפחות.",
    recommendedTents: ["familia", "hub-shelter-pro"],
    recommendedAccessories: ["dining-set", "garlands"],
    parksUrl: "https://cityofdavid.org.il/sites/peace-forest/",
  },
]

export function getLocationsByRegion(region: RegionType): CampingLocation[] {
  return locations.filter((l) => l.region === region)
}

export function getLocationsByLandscape(landscape: LandscapeType): CampingLocation[] {
  return locations.filter((l) => l.landscape === landscape)
}

export const amenityLabels: Record<string, string> = {
  water:       "מים",
  toilets:     "שירותים",
  shade:       "צל",
  tables:      "שולחנות",
  electricity: "חשמל",
  shower:      "מקלחות",
  glamping:    "גלמפינג",
}
